
#ifndef SIGNAL_H
#define SIGNAL_H

#include <sys/types.h>

union sigval
{
    int sival_int; /* Integer signal value. */
    void *sival_ptr; /* Pointer signal value. */
};

typedef struct
{
    int           si_signo  ; /* Signal number. */
    int           si_code   ; /* Signal code. */
    int           si_errno  ; /* If non-zero, an errno value associated with this signal, as described in <errno.h>. */
    pid_t         si_pid    ; /* Sending process ID. */
    uid_t         si_uid    ; /* Real user ID of sending process. */
    void         *si_addr   ; /* Address of faulting instruction. */
    int           si_status ; /* Exit value or signal. */
    long          si_band   ; /* Band event for SIGPOLL. */
    union sigval  si_value  ; /* Signal value. */
} siginfo_t;

#include_next <signal.h>

#define sa_sigaction sa_handler

typedef int pthread_attr_t; /* TODO: something about it in sys/types.h */

struct sigevent
{
    int sigev_notify; /* Notification type. */
    int sigev_signo;  /* Signal number. */
    union sigval sigev_value; /* Signal value. */
    void (*sigev_notify_function)(union sigval); /* Notification function. */
    pthread_attr_t *sigev_notify_attributes; /* Notification attributes. */ 
};

#define SIGEV_NONE 0 /* No asynchronous notification is delivered when the event of interest occurs. */
#define SIGEV_SIGNAL 1 /* A queued signal, with an application-defined value, is generated when the event of interest occurs. */
#define SIGEV_THREAD 2 /* A notification function is called to perform notification. */

#define SA_NOCLDSTOP   1 /* Do not generate SIGCHLD when children stop */
#define SA_ONSTACK     2 /* Causes signal delivery to occur on an alternate stack. */
#define SA_RESETHAND   4 /* Causes signal dispositions to be set to SIG_DFL on entry to signal handlers. */
#define SA_RESTART     8 /* Causes certain functions to become restartable. */
#define SA_SIGINFO    16 /* Causes extra information to be passed to signal handlers at the time of receipt of a signal. */
#define SA_NOCLDWAIT  32 /* Causes implementations not to create zombie processes or status information on child termination. See sigaction. */
#define SA_NODEFER    64 /* Causes signal not to be automatically blocked on entry to signal handler. */

#define ILL_ILLOPC 10 /* Illegal opcode. */
#define ILL_ILLOPN 10 /* Illegal operand. */
#define ILL_ILLADR 10 /* Illegal addressing mode. */
#define ILL_ILLTRP 10 /* Illegal trap. */
#define ILL_PRVOPC 10 /* Privileged opcode. */
#define ILL_PRVREG 10 /* Privileged register. */
#define ILL_COPROC 10 /* Coprocessor error. */
#define ILL_BADSTK 20 /* Internal stack error. */
#define FPE_INTDIV 21 /* Integer divide by zero. */
#define FPE_INTOVF 22 /* Integer overflow. */
#define FPE_FLTDIV 23 /* Floating-point divide by zero. */
#define FPE_FLTOVF 24 /* Floating-point overflow. */
#define FPE_FLTUND 25 /* Floating-point underflow. */
#define FPE_FLTRES 26 /* Floating-point inexact result. */
#define FPE_FLTINV 27 /* Invalid floating-point operation. */
#define FPE_FLTSUB 28 /* Subscript out of range. */
#define SEGV_MAPERR 30 /* Address not mapped to object. */
#define SEGV_ACCERR 31 /* Invalid permissions for mapped object. */
#define BUS_ADRALN 40 /* Invalid address alignment. ￼ */
#define BUS_ADRERR 41 /* Nonexistent physical address. */
#define BUS_OBJERR 42 /* Object-specific hardware error. */
#define TRAP_BRKPT 50 /* Process breakpoint. */
#define TRAP_TRACE 51 /* Process trace trap. ￼ */
#define CLD_EXITED 60 /* Child has exited. */
#define CLD_KILLED 61 /* Child has terminated abnormally and did not create a core file. */
#define CLD_DUMPED 62 /* Child has terminated abnormally and created a core file. */
#define CLD_TRAPPED 63 /* Traced child has trapped. */
#define CLD_STOPPED 64 /* Child has stopped. */
#define CLD_CONTINUED 65 /* Stopped child has continued. ￼ */
#define POLL_IN 70 /* Data input available. */
#define POLL_OUT 71 /* Output buffers available. */
#define POLL_MSG 72 /* Input message available. */
#define POLL_ERR 73 /* I/O error. */
#define POLL_PRI 74 /* High priority input available. */
#define POLL_HUP 75 /* Device disconnected. ￼ */
#define SI_USER    1 /* Signal sent by kill(). */
#define SI_QUEUE   2 /* Signal sent by sigqueue(). */
#define SI_TIMER   3 /* Signal generated by expiration of a timer set by timer_settime(). */
#define SI_ASYNCIO 4 /* Signal generated by completion of an asynchronous I/O request. */
#define SI_MESGQ   5 /* Signal generated by arrival of a message on an empty message queue. */

int killpg (pid_t, int);
int sigaction (int, const struct sigaction *, struct sigaction *);
int sigaddset (sigset_t *, const int);
int sigdelset (sigset_t *, const int);
int sigismember (const sigset_t *, int);
int sigfillset (sigset_t *);
int sigemptyset (sigset_t *);
int sigpending (sigset_t *);
int sigsuspend (const sigset_t *);
int sigpause (int);
int siginterrupt(int, int);
int sighold(int);
int sigrelse(int);
int sigignore(int);

#endif /* SIGNAL_H */

